pub mod agent;
pub mod agent_driver;
pub mod approval;
pub mod cache_keepalive;
pub mod code_intel;
pub mod context_view;
pub mod cost;
pub mod harness;
pub mod hooks;
pub mod plugin;
pub mod plugin_protocol;

/// Cap'n Proto generated types for the plugin wire protocol.
///
/// Schema: `schema/plugin.capnp`. Generated by `build.rs` into `$OUT_DIR`.
/// Types are accessed as `nca_core::plugin_capnp::body::Which(...)` etc.
pub mod plugin_capnp {
    include!(concat!(env!("OUT_DIR"), "/schema/plugin_capnp.rs"));
}
pub mod provider;
pub mod skill_installer;
pub mod skills;
pub mod tool_guards;
pub mod tool_pipeline;
pub mod tools;
pub mod workspace_fs;
